sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
  - "8"
  - "6"

script: npm run travis

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - bash <(curl -s https://codecov.io/bash) -F $JOB_PART -X gcov
  - rm -rf ./coverage
