sudo: false
dist: trusty
language: node_js

stages:
  - basic
  - advanced

matrix:
  include:
    - os: linux
      node_js: "10"
      stage: basic
    - os: osx
      node_js: "10"
      stage: basic
    - os: linux
      node_js: "10"
      env: WATCHPACK_POLLING=200
      stage: advanced
    - os: linux
      node_js: "8"
      stage: advanced
    - os: linux
      node_js: "8"
      env: WATCHPACK_POLLING=200
      stage: advanced
    - os: linux
      node_js: "6"
      stage: advanced
    - os: linux
      node_js: "6"
      env: WATCHPACK_POLLING=200
      stage: advanced
    - os: osx
      node_js: "8"
      stage: advanced
    - os: osx
      node_js: "6"
      stage: advanced

script:
  - yarn cover --report lcovonly

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - bash <(curl -s https://codecov.io/bash) -F $JOB_PART -X gcov
  - rm -rf ./coverage
