# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 14
    - nodejs_version: 12
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn --frozen-lockfile

build: off

test_script:
  - node --version
  - npm --version
  - yarn --version
  - cmd: yarn test
